### PR TITLE
Restore scipy >= 1.18 compatibility (fixes #134)

### LINKED ISSUE #134: scipy 1.18 has broken a lot
Scipy 1.18 has basically broken  pwlf. It is more than just keyword arguments being wrong. I'm seeing NaNs which is not a good thing (seeing this with both fit and fitfast functions, and I have seen NaN standard errors). I'm guessing it is either the differential evolution or least squares. I'll need more time to debug this. I have ~5 test failing after fixing the keyword argument changes.

Please consider not using pwlf with scipy 1.18.

This is much worse than than just a keyword argument change. I spent a couple hours today debugging examples. 

I'm going to push a patch that limits the version to scipy <= 1.17 in the meantime.

Related issues
https://github.com/cjekel/piecewise_linear_fit_py/issues/133
https://github.com/cjekel/piecewise_linear_fit_py/issues/132

### PR DESCRIPTION
**Pull request by chaoz23**
Fixes #134.

## Problem

Under scipy 1.18, `fit()` and `fitfast()` break — `fitfast()` raises `ValueError: All-NaN slice encountered` and `fit()` can converge to wrong breakpoints. This reproduces the "seeing NaNs ... ~5 tests failing" you described in #134. On this branch, `python -m pytest tests/tests.py` under scipy 1.18.0 fails 5 tests on current `master`:

```
FAILED test_all_stats       - ValueError: All-NaN slice encountered
FAILED test_fit             - AssertionError
FAILED test_fit_guess       - AssertionError
FAILED test_fit_guess_kwrds - TypeError: fmin_l_bfgs_b() got an unexpected keyword argument 'iprint'
FAILED test_fitfast         - AssertionError
```

## Root cause

scipy 1.18 changed `scipy.linalg.lstsq`: for a **rank-deficient / degenerate** system it now returns a **`NaN` residual** instead of raising `LinAlgError` — and it does so *even when `beta` itself is finite*. This happens during optimization whenever a trial puts an interior breakpoint on the domain boundary (coincident breakpoints), e.g. `var = [4.52, 10.0]`:

```python
beta, ssr, rank, s = linalg.lstsq(A, y, lapack_driver="gelsd")
# scipy 1.17: raises LinAlgError (caught -> ssr=inf)
# scipy 1.18: rank=5, beta finite, ssr = array(nan)   <-- silent NaN
```

`lstsq()` only recomputed `ssr` manually when the residual array was *empty*, and `fit_with_breaks_opt()` only guarded against `LinAlgError`/`None` — so the `NaN` leaked into the objective. That `NaN` then poisons `fitfast`'s `np.nanargmin` (all trials `NaN` → "All-NaN slice") and misdirects the global optimization in `fit`.

## Fix

- **`lstsq()`** — recompute the residual sum of squares from `beta` whenever scipy returns a **non-finite** residual, mirroring the existing empty-residual path. Since `beta` is finite in the degenerate case, this yields the *correct* finite `ssr` (verified to match scipy's own residual exactly at non-degenerate points).
- **`fit_with_breaks_opt()`** — return `np.inf` for any non-finite fit, so the optimizer steers away from truly singular breakpoints (restores pre-1.18 behavior).
- **`setup.py`** — remove the temporary `scipy < 1.18.0` upper bound added in 2.5.3.
- **tests** — drop the `iprint`/`disp` kwargs (removed from `fmin_l_bfgs_b` in scipy 1.18) from the keyword-passthrough test, and add a regression test for the degenerate-breakpoint NaN case.

The change is inert on older scipy (the recompute only triggers when the returned residual is non-finite, which pre-1.18 never returns), so existing behavior is unchanged.

## Test evidence

All tests pass on both the new and previously-supported scipy:

| scipy | result |
|---|---|
| 1.18.0 | `63 passed` |
| 1.17.1 | `63 passed` |

(63 = the existing 62 plus the new `test_degenerate_breaks_finite_ssr` regression test.)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by cjekel** [comment]
LGTM! Thank you.

**Comment by cjekel** [comment]
It is cleaner than the fix I was working on. I got hung up in the lstsq changes, and my attempted fix was still running into edge cases.
